version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: if [[ -n $(gofmt -l .) ]]; then echo "Please run gofmt"; exit 1; fi
      - run: go vet -tags bls377 -v ./...
      - run: go vet -tags bls381 -v ./...
      - run: go vet -tags bn256 -v ./...
      - run: go test -v ./cmd/ -run=VersionIsGenerated # ensure version is generated
      - run: go get golang.org/x/tools/cmd/goimports
      - run: go generate ./...
      - run: go test -v -short -tags debug ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"